# Generated by Django 5.0.4 on 2024-05-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='deadline',
        ),
    ]
