# Generated by Django 5.0.4 on 2024-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
